# Welcome to Lab: Simpson's Paradox 🔬

Before this lab section, you learned about Simpson's Paradox and confounding variables in lecture.  This week, you will find Simpson's Paradox through analysis of a dataset in Python, and get some practice writing conditionals for pandas DataFrames! 

A few tips to remember:

- **You are not alone on your journey in learning programming!**  You have your lab Teaching Assistant, your Course Aides, your lab group, and the professors (Prof. Wade and Prof. Karle), who are all here to help you out!
- If you find yourself stuck for more than a few minutes, ask a neighbor or course staff for help!  When you are giving help to your neighbor, explain the **idea and approach** to the problem without sharing the answer itself so they can have the same **<i>ah-hah</i>** moment!
- We are here to help you!  Don't feel embarrassed or shy to ask us for help!

Let's get started!

In [ ]:
# Meet your CAs and TA if you haven't already!
# ...first name is enough, we'll know who they are! :)
ta_name = "Kim"
ca1_name = "Mia"
ca2_name = "Jai"


# Say hello to each other!
# - Groups of 3 are ideal :)
# - However, groups of 2 or 4 are fine too!
#
# Question of the Day (QOTD) to Ask Your Group: "Have you heard of ChatGPT?"
partner1_name = "Brian"
partner1_netid = "bmarty64"
partner1_chatgpt = "Yes"

partner2_name = "Toby"
partner2_netid = "tgort2"
partner2_chatgpt = "Yes"

partner3_name = "Kasra"
partner3_netid = "kvaki2"
partner3_chatgpt= "Yes"

<hr style="color: #DD3403;">

# Part 1: The GPA Dataset

Many of you have likely come across one of the GPA visualizations found at https://waf.cs.illinois.edu/discovery/gpa/, either out of 
curiosity or the need to investigate a mysterious GenEd class you signed up for. 

Regardless, these visualizations are built on the **GPA Dataset** of UIUC students across all course subjects. Today, you're going to do some analysis and discover a case of Simpson's Paradox within data taken from UIUC courses!

## Load the GPA Dataset

The most recent version of the "GPA Dataset" is available here:
```
https://waf.cs.illinois.edu/discovery/gpa.csv
```

Use Python to load this dataset into a DataFrame called `df`:

In [15]:
import pandas as pd
df= pd.read_csv("https://waf.cs.illinois.edu/discovery/gpa.csv")
df

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C+,C,C-,D+,D,D-,F,W,Primary Instructor,Students
0,2022,Spring,2022-sp,AAS,100,Intro Asian American Studies,LCD,6,13,0,...,0,3,0,1,1,0,0,0,"Lee, Sang S",29
1,2022,Spring,2022-sp,AAS,100,Intro Asian American Studies,DIS,0,11,5,...,1,0,1,1,0,0,0,0,"Zheng, Reanne",25
2,2022,Spring,2022-sp,AAS,100,Intro Asian American Studies,DIS,0,10,7,...,0,0,0,0,0,0,2,0,"Zheng, Reanne",27
3,2022,Spring,2022-sp,AAS,100,Intro Asian American Studies,DIS,17,8,1,...,0,0,0,0,0,0,0,0,"Rosado-Torres, Alexander",28
4,2022,Spring,2022-sp,AAS,100,Intro Asian American Studies,OD,0,8,4,...,1,0,0,0,0,1,3,1,"Wang, Yu",21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64043,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,0,1,3,0,0,0,2,1,"Stepanov, Alexei G",31
64044,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,0,"Unger, David",28
64045,2010,Summer,2010-su,TAM,212,Introductory Dynamics,LEC,0,1,3,...,5,1,1,0,2,0,1,0,"Morgan, William T",28
64046,2010,Summer,2010-su,TAM,251,Introductory Solid Mechanics,LCD,1,2,2,...,3,3,2,0,0,1,1,0,"Ott-Monsivais, Stephanie",21
64047,2010,Summer,2010-su,TAM,335,Introductory Fluid Mechanics,LEC,5,8,9,...,0,4,0,0,1,0,2,0,"Keane, Richard D",39

### 🔬 Test Case Checkpoint 🔬

In [13]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert(len(df) == 64048 ), "This is not the GPA dataset you're looking for"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

## Data Cleaning: An Additional Column

The GPA dataset contains raw GPA data and is not the easiest to work with if we want to analyze intricacies such as the average GPA or passing rate.  Luckily, DataFrames are modifiable, so we can **add more columns** based on what questions we want to answer.

The process of modifying a dataset via deletion (cleaning up empty/unwanted values) or addition (adding new columns) is often called **data cleaning**. This is an important concept in Data Science, because you won't always receive your data in the perfect format for your purposes.

With the GPA dataset, we want to investigate one innocent question posed by a theoretical incoming student: 
- *Is it easier to get an A in STAT or CS courses at UIUC?*

To do this, we'll need to first perform some modifications on our loaded DataFrame, `df`. Specifically, we will need to create:
- An `A_Grade` column, containing the total number of students receiving an A+, A, or A- in every course

### Puzzle 1.1: Creating an `A_Grade` Column

Create the new column `A_Grade` that stores the total number of "A"s given in every course.

- We consider an "A" to be any type of A, in other words "A+", "A", or an "A-" are all included.
- In our `df`, the number of students recieving a particular grade in a course is found in the `df['Grade']` column. For example, `df['A']` contains the number of students who recieved an A

In [23]:
df['A_Grade'] = df['A'] + df['A+'] + df['A-'] 
df['A_Grade']

0        19
1        16
2        17
3        26
4        12
         ..
64043    17
64044    24
64045     4
64046     5
64047    22
Name: A_Grade, Length: 64048, dtype: int64

### 🔬 Test Case Checkpoint 🔬

In [18]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert('A_Grade' in df), "Make sure you've named the A_Grade column properly and added it to the dataframe"
assert(df['A_Grade'].sum() == 2096341), "Double check the values of your A_Grade column"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

# Part 1: Working with the GPA Dataset
Now that we have that extra column set up, we can perform basic mathematical analysis on the GPA Dataset to get insight towards our question:
- *Is it easier to get an A in STAT or CS courses at UIUC?*

Should be simple, right? Let's just see which subject, STAT or CS, has a greater percentage of A grades .

### Puzzle 1.2: Subject DataFrames

Select only the rows of the GPA dataset `df` with a `Subject` of `STAT`. Assign these rows to a new DataFrame, `df_STAT`. 
- Make sure your result only contains STAT courses!

In [20]:
df_STAT = df[df.Subject == 'STAT']
df_STAT

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Students,A_Grade
2172,2022,Spring,2022-sp,STAT,100,Statistics,LEC,186,106,55,...,30,10,14,10,8,11,2,"Flanagan, Karle A",582,347
2173,2022,Spring,2022-sp,STAT,100,Statistics,ONL,178,126,72,...,24,19,11,15,12,16,2,"Flanagan, Karle A",663,376
2174,2022,Spring,2022-sp,STAT,100,Statistics,ONL,19,21,4,...,0,3,0,2,2,9,1,"Reger, William J",84,44
2175,2022,Spring,2022-sp,STAT,107,Data Science Discovery,LEC,9,125,24,...,5,2,6,2,1,10,2,"Flanagan, Karle A",230,158
2176,2022,Spring,2022-sp,STAT,200,Statistical Analysis,ONL,57,131,41,...,13,4,2,0,2,9,2,"Fireman, Ellen S",350,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64040,2010,Summer,2010-su,STAT,100,Statistics,LCD,1,13,3,...,2,2,3,1,1,1,0,"Hirtz, Nathaniel R",39,17
64041,2010,Summer,2010-su,STAT,100,Statistics,LCD,0,14,3,...,3,0,0,1,0,3,1,"Dalpiaz, David M",28,17
64042,2010,Summer,2010-su,STAT,400,Statistics and Probability I,LEC,4,15,7,...,2,2,0,1,0,3,1,"Monrad, Ditlev",47,26
64043,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,1,3,0,0,0,2,1,"Stepanov, Alexei G",31,17
64044,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,"Unger, David",28,24

Select only the rows of the GPA dataset `df` with a `Subject` of `CS`. Assign these rows to a new dataframe, `df_CS`. 
- Make sure your result only contains CS courses!

In [21]:
df_CS = df[df.Subject == 'CS']
df_CS

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Students,A_Grade
712,2022,Spring,2022-sp,CS,101,Intro Computing: Engrg & Sci,OLC,155,340,55,...,3,6,4,6,0,17,1,"Davis, Neal E",642,550
713,2022,Spring,2022-sp,CS,105,Intro Computing: Non-Tech,OLC,12,62,17,...,16,14,3,4,4,9,2,"Zilles, Craig",193,91
714,2022,Spring,2022-sp,CS,105,Intro Computing: Non-Tech,OLC,28,101,26,...,19,20,4,9,2,10,3,"Zilles, Craig",308,155
715,2022,Spring,2022-sp,CS,124,Intro to Computer Science I,OLC,70,314,43,...,9,9,0,18,0,28,4,"Challen, Geoffrey W",578,427
716,2022,Spring,2022-sp,CS,126,Software Design Studio,LCD,47,105,25,...,1,0,1,3,2,5,0,"Woodley, Michael J",203,177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63924,2010,Summer,2010-su,CS,101,Intro Computing: Engrg & Sci,LBD,4,6,2,...,0,1,0,0,0,0,0,"Gambill, Thomas N",21,12
63925,2010,Summer,2010-su,CS,225,Data Structures,LBD,1,5,1,...,3,1,0,2,0,1,0,"Earls, John C",21,7
63926,2010,Summer,2010-su,CS,373,Theory of Computation,LEC,5,1,5,...,0,2,0,2,0,1,1,"Kumar, Viraj",26,11
63927,2010,Summer,2010-su,CS,421,Progrmg Languages & Compilers,LCD,2,5,5,...,1,4,0,4,0,0,1,"Hafiz, Munawar",30,12
63928,2010,Summer,2010-su,CS,598,Object-Oriented Prog & Design,ONL,3,22,0,...,0,0,0,0,0,0,0,"Johnson, Ralph E",30,25

### 🔬 Test Case Checkpoint 🔬

In [22]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.
assert( 'df_STAT' in vars() ), "Make certain to name the STAT courses df_STAT."
assert( 'df_CS' in vars() ), "Make certain to name the CS courses df_CS."
assert( len(df_STAT[df_STAT.Subject != "STAT"] ) == 0 ), "It looks like you did not subset df_STAT to only STAT courses."
assert( len(df_CS[df_CS.Subject != "CS"] ) == 0 ), "It looks like you did not subset df_STAT to only STAT courses."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 1.3: Comparing Overall Percentages

With our two new dataframes of STAT and CS courses, use the following code cell to determine the **percentage** of A grades recieved in STAT and CS courses, storing them as variables `stat_a` and `cs_a` respectively. 

Print statements have been provided to show the values you calculate. 

As you work, remember:
- To find the **% of As**, divide the total number of `A_Grade`s by the total number of `Students` ($\space \frac{A \space Grades}{Students} \space$)
- The `A_Grade` column you made earlier, and the `Students` column containing the total number of students in each course.
- The syntax `sum(df['column_name'])` can be used to add up the values of all rows in a particular column of a DataFrame.

In [33]:
stat_a = sum(df_STAT['A_Grade']) / (sum(df_STAT['Students']))
print(f'Overall % of As in STAT is: {stat_a}')

cs_a = sum(df_CS['A_Grade']) / (sum(df_CS['Students']))
print(f'Overall % of As in CS is: {cs_a}')

Overall % of As in STAT is: 0.6051620045305918
Overall % of As in CS is: 0.596793417279641

### 🔬 Test Case Checkpoint 🔬

In [34]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
import math
assert(math.isclose(stat_a, 0.6051620045305918)), "The overall percentage of A grades recieved in STAT courses does not appear to have been correctly calculated"
assert(math.isclose(cs_a, 0.596793417279641)), "The overall percentage of A grades recieved in CS courses does not appear to have been correctly calculated"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Analysis: Good Comparison?
**Q: What conclusion can you take from the overall percentages found above when asking the original question:**
- *Is it easier to get an A in STAT or CS courses at UIUC?*

It is easier to get an A in STAT because the percentage of As in STAT is higher than CS

**Q: Given what you've learned about experimental design, what are some reasons (specific to this dataset) you may not trust this conclusion? If you would trust it, explain why.**

I may not trust this conclusion as a percentage because these two percentages are comparing four different variables of A's and total students in both STAT/CS. I think this could be an example of Simpsons Paradox.

## An Extra Consideration

If you look at the `Year` column of our GPA dataset, you might notice that we have some old data in our set - all the way back to **2010**! This means we aren't really answering our question from the perspective of a student now. 

If we want to know if it is easier to **currently** get an A in a STAT or CS course, we should control for the **date** of the data by looking at more **recent years** specifically.

### Puzzle 1.4: More DataFrames

Using the code cells below, define four new DataFrames by selecting from rows of our previously created `df_CS` and `df_STAT`. 

- `df_cs_recent`: all `CS` course data in *recent years* ($\space \geq 2021 \space$)
- `df_stat_recent`: all `STAT` course data in *recent years* ($\space \geq 2021 \space$)
- `df_cs_old`: all other, older `CS` course data ($\space < 2021 \space$)
- `df_stat_old`: all other, older `STAT` course data ($\space < 2021 \space$)

Define *recent years* as **any year after and including 2021**, and older years as any year before 2021. 

Feel free to use conditionals OR the `.isin()` syntax you learned in the last lab.

In [35]:
df_stat_recent = df_STAT[df_STAT['YearTerm'] >= '2021']
df_stat_recent

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Students,A_Grade
2172,2022,Spring,2022-sp,STAT,100,Statistics,LEC,186,106,55,...,30,10,14,10,8,11,2,"Flanagan, Karle A",582,347
2173,2022,Spring,2022-sp,STAT,100,Statistics,ONL,178,126,72,...,24,19,11,15,12,16,2,"Flanagan, Karle A",663,376
2174,2022,Spring,2022-sp,STAT,100,Statistics,ONL,19,21,4,...,0,3,0,2,2,9,1,"Reger, William J",84,44
2175,2022,Spring,2022-sp,STAT,107,Data Science Discovery,LEC,9,125,24,...,5,2,6,2,1,10,2,"Flanagan, Karle A",230,158
2176,2022,Spring,2022-sp,STAT,200,Statistical Analysis,ONL,57,131,41,...,13,4,2,0,2,9,2,"Fireman, Ellen S",350,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7541,2021,Summer,2021-su,STAT,400,Statistics and Probability I,OLC,11,22,6,...,4,3,2,1,0,7,2,"Nguyen, Ha Khanh",84,39
7542,2021,Summer,2021-su,STAT,410,Statistics and Probability II,ONL,8,14,4,...,3,0,0,3,0,4,2,"Stepanov, Alexey G",56,26
7543,2021,Summer,2021-su,STAT,420,Statistical Modeling in R,ONL,101,94,15,...,1,0,0,0,0,2,4,"Unger, David",227,210
7544,2021,Summer,2021-su,STAT,420,Methods of Applied Statistics,ONL,5,8,1,...,2,0,0,0,0,1,0,"Unger, David",22,14
7545,2021,Summer,2021-su,STAT,425,Applied Regression and Design,ONL,13,13,8,...,0,1,0,0,0,5,0,"Bravo De Guenni, Lelys",45,34

In [36]:
df_cs_recent = df_CS[df_CS['YearTerm'] >= '2021']
df_cs_recent

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Students,A_Grade
712,2022,Spring,2022-sp,CS,101,Intro Computing: Engrg & Sci,OLC,155,340,55,...,3,6,4,6,0,17,1,"Davis, Neal E",642,550
713,2022,Spring,2022-sp,CS,105,Intro Computing: Non-Tech,OLC,12,62,17,...,16,14,3,4,4,9,2,"Zilles, Craig",193,91
714,2022,Spring,2022-sp,CS,105,Intro Computing: Non-Tech,OLC,28,101,26,...,19,20,4,9,2,10,3,"Zilles, Craig",308,155
715,2022,Spring,2022-sp,CS,124,Intro to Computer Science I,OLC,70,314,43,...,9,9,0,18,0,28,4,"Challen, Geoffrey W",578,427
716,2022,Spring,2022-sp,CS,126,Software Design Studio,LCD,47,105,25,...,1,0,1,3,2,5,0,"Woodley, Michael J",203,177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7393,2021,Summer,2021-su,CS,416,Data Visualization,ONL,265,113,25,...,0,0,0,0,0,3,8,"Hart, John C",432,403
7394,2021,Summer,2021-su,CS,421,Progrmg Languages & Compilers,ONL,50,20,5,...,2,0,0,2,0,4,2,"Beckman, Mattox A",92,75
7395,2021,Summer,2021-su,CS,421,Progrmg Languages & Compilers,OLC,17,8,6,...,4,0,0,6,0,5,3,"Beckman, Mattox A",62,31
7396,2021,Summer,2021-su,CS,598,Cloud Capstone,ONL,55,15,3,...,1,0,0,1,0,0,0,"Farivar, Reza",75,73
7397,2021,Summer,2021-su,CS,598,Data Mining Capstone,ONL,11,16,1,...,0,0,0,0,0,0,0,"Farivar, Reza",29,28

In [37]:
df_stat_old = df_STAT[df_STAT['YearTerm'] < '2021']
df_stat_old

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Students,A_Grade
9790,2020,Fall,2020-fa,STAT,100,Statistics,ONL,402,283,159,...,43,34,15,15,5,35,0,"Flanagan, Karle A",1340,844
9791,2020,Fall,2020-fa,STAT,107,Data Science Discovery,OLC,22,86,13,...,4,4,1,0,0,5,0,"Nguyen, Ha Khanh",163,121
9792,2020,Fall,2020-fa,STAT,200,Statistical Analysis,ONL,26,1,3,...,1,0,3,1,0,1,0,"Ellison, Victoria M",40,30
9793,2020,Fall,2020-fa,STAT,200,Statistical Analysis,ONL,60,112,39,...,9,6,1,4,0,1,0,"Fireman, Ellen S",319,211
9794,2020,Fall,2020-fa,STAT,212,Biostatistics,ONL,50,80,39,...,4,4,1,2,1,1,0,"Findley, Kelly P",242,169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64040,2010,Summer,2010-su,STAT,100,Statistics,LCD,1,13,3,...,2,2,3,1,1,1,0,"Hirtz, Nathaniel R",39,17
64041,2010,Summer,2010-su,STAT,100,Statistics,LCD,0,14,3,...,3,0,0,1,0,3,1,"Dalpiaz, David M",28,17
64042,2010,Summer,2010-su,STAT,400,Statistics and Probability I,LEC,4,15,7,...,2,2,0,1,0,3,1,"Monrad, Ditlev",47,26
64043,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,1,3,0,0,0,2,1,"Stepanov, Alexei G",31,17
64044,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,"Unger, David",28,24

In [38]:
df_cs_old = df_CS[df_CS['YearTerm'] < '2021']
df_cs_old

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Students,A_Grade
8276,2020,Fall,2020-fa,CS,100,Freshman Orientation,ONL,0,267,2,...,0,0,0,1,0,1,0,"Gunter, Elsa",277,269
8277,2020,Fall,2020-fa,CS,100,Freshman Orientation,OLC,0,17,1,...,0,0,1,0,0,1,0,"Gunter, Elsa",22,18
8278,2020,Fall,2020-fa,CS,101,Intro Computing: Engrg & Sci,OLC,181,191,19,...,2,5,1,1,0,5,0,"Davis, Neal E",434,391
8279,2020,Fall,2020-fa,CS,105,Intro Computing: Non-Tech,OLC,31,105,72,...,20,17,3,2,2,14,0,"Zilles, Craig",420,208
8280,2020,Fall,2020-fa,CS,105,Intro Computing: Non-Tech,OLC,20,45,27,...,4,3,3,2,1,6,0,"Zilles, Craig",174,92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63924,2010,Summer,2010-su,CS,101,Intro Computing: Engrg & Sci,LBD,4,6,2,...,0,1,0,0,0,0,0,"Gambill, Thomas N",21,12
63925,2010,Summer,2010-su,CS,225,Data Structures,LBD,1,5,1,...,3,1,0,2,0,1,0,"Earls, John C",21,7
63926,2010,Summer,2010-su,CS,373,Theory of Computation,LEC,5,1,5,...,0,2,0,2,0,1,1,"Kumar, Viraj",26,11
63927,2010,Summer,2010-su,CS,421,Progrmg Languages & Compilers,LCD,2,5,5,...,1,4,0,4,0,0,1,"Hafiz, Munawar",30,12
63928,2010,Summer,2010-su,CS,598,Object-Oriented Prog & Design,ONL,3,22,0,...,0,0,0,0,0,0,0,"Johnson, Ralph E",30,25

### 🔬 Test Case Checkpoint 🔬

In [39]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.
assert( 'df_stat_recent' in vars() ), "Make certain to name the recent STAT courses df_stat_recent."
assert( 'df_cs_recent' in vars() ), "Make certain to name the recent CS courses df_cs_recent."
assert( 'df_stat_old' in vars() ), "Make certain to name the old STAT courses df_stat_old."
assert( 'df_cs_old' in vars() ), "Make certain to name the old CS courses df_cs_old."

assert( len(df_stat_recent[df_stat_recent.Year < 2021] ) == 0 ), "Make sure only years after and including 2021 are in the df_stat_recent dataframe."
assert( len(df_cs_recent[df_cs_recent.Year < 2021] ) == 0 ), "Make sure only years after and including 2021 are in the df_cs_recent dataframe."
assert( len(df_stat_old[df_stat_old.Year >= 2021] ) == 0 ), "Make sure only years before 2021 are in the df_stat_old dataframe."
assert( len(df_cs_old[df_cs_old.Year >= 2021] ) == 0 ), "Make sure only years before 2021 are in the df_cs_old dataframe."

assert( len(df[ df.index.isin(df_stat_recent.index) & df.index.isin(df_stat_old.index) ]) == 0 ), "Check for duplicate values in your df_stat_recent and df_stat_old dataframes."
assert( len(df[ df.index.isin(df_cs_recent.index) & df.index.isin(df_cs_old.index) ]) == 0 ), "Check for duplicate values in your df_cs_recent and df_cs_old dataframes."
assert( len(df_cs_old) + len(df_cs_recent) == len(df_CS) ), "You're excluding some rows from df_cs_old or df_cs_young. Please double check your conditionals."
assert( len(df_stat_old) + len(df_stat_recent) == len(df_STAT) ), "You're excluding some rows from df_stat_old or df_stat_recent. Please double check your conditionals."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 1.5: New Analysis
Now that we've got all the DataFrames setup with GPA data of the `CS` and `STAT` courses separated by recency (2021 or newer being 'recent'), we can do more in-depth analysis to investigate our question. 

In the following code cells, **calculate the percentages** described by the comment in the cell. Your answer should always be a **decimal between 0 and 1**. 

Just like Puzzle 1.2, remember: 
- To find the % of As, divide the total number of students by the total number of As 
- The `A_Grade` column you made earlier, and the `Students` column containing the total number of students in each course.
- The syntax `sum(df['column_name'])` can be used to add up the values of all rows in a particular column of a DataFrame.

In [40]:
# Percentage of As received in CS in recent years
cs_recent_a = sum(df_cs_recent['A_Grade']) / (sum(df_cs_recent['Students']))
print(f'Percentage of As received in CS in recent years: {cs_recent_a}')

Percentage of As received in CS in recent years: 0.7052750783492665

In [41]:
# Percentage of As received in STAT in recent years
stat_recent_a = sum(df_stat_recent['A_Grade']) / (sum(df_stat_recent['Students']))
print(f'Percentage of As received in STAT in recent years: {stat_recent_a}')

Percentage of As received in STAT in recent years: 0.6488539077602872

In [42]:
# percentage of As received in CS in older years
cs_old_a = sum(df_cs_old['A_Grade']) / (sum(df_cs_old['Students']))
print(f'Percentage of As received in CS in older years: {cs_old_a}')

Percentage of As received in CS in older years: 0.5714531786360225

In [45]:
# percentage of As received in STAT in older years
stat_old_a = sum(df_stat_old['A_Grade']) / (sum(df_stat_old['Students']))
print(f'Percentage of As received in STAT in older years: {stat_old_a}')

Percentage of As received in STAT in older years: 0.5975443876015648

### 🔬 Test Case Checkpoint 🔬

In [46]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert(math.isclose(cs_recent_a,  0.7052750783492665)), "The overall percentage of A grades recieved in STAT courses recently does not appear to have been correctly calculated"
assert(math.isclose(stat_recent_a, 0.6488539077602872)), "The overall percentage of A grades recieved in CS courses recently does not appear to have been correctly calculated"

assert(math.isclose(cs_old_a, 0.5714531786360225)), "The overall percentage of A grades recieved in STAT courses in older years does not appear to have been correctly calculated"
assert(math.isclose(stat_old_a, 0.5975443876015648)), "The overall percentage of A grades recieved in CS courses in older years does not appear to have been correctly calculated"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Observe the Results
**Run the following cell** to format all of your answers as a DataFrame.

Keep in mind that "Older" means data from courses **before 2021**, and "Recent" means courses held **during or after 2021**.

In [47]:
pd.DataFrame([
  {'Older % of A': cs_old_a, 'Recent % of A': cs_recent_a, 'Overall % of A': cs_a},
  {'Older % of A': stat_old_a, 'Recent % of A': stat_recent_a, 'Overall % of A': stat_a}
], index=['CS', 'STAT'])

      Older % of A  Recent % of A  Overall % of A
CS        0.571453       0.705275        0.596793
STAT      0.597544       0.648854        0.605162

Notice that when observing the overall % of A grades received, you may think `STAT` and `CS` are equally difficult to get an `A_Grade` in. But in the sub-group of the courses held in years of **2021 and later**, we see that `CS` actually has a higher `A_Grade` rate! 

This is **Simpson's Paradox**: a pattern within a population can appear, disappear, or reverse when you look at subpopulations.

In more formal terms, Simpson's Paradox can cause you to observe a pattern reverse when you look at the overall group statistics versus statistics of groups post-stratification. In this case we are stratifying by time.

### Analysis: Reflecting on New Observations

You should see the pattern reverse when you look at the overall A grade percentages vs. the percentages stratified to account for recency. This is called **Simpson's Paradox**: a pattern within a population can appear, disappear, or reverse when you look at subpopulations.

Now think about how would you now respond differently to the incoming student's question:
- *Is it easier to get an A in STAT or CS courses at UIUC?*

**Q: Which comparison of percentages do you trust more and why? Are there any other potential confounding variables when answering this question that could be investigated further? Respond with at least three full sentences.**

I trust the comparison of percentages of recent percentages more because the data is more relevant to the person investigating. I think that another confounder could possibly be the total number of students in both subjects or the undergraduate/graduate level courses. I think it is easier to get an A in CS courses in recent years, as the percentages of the A's went up over 10%! This shows to me that the CS coursework must have changed in some way to lead to this percentage.

<hr style="color: #DD3403;">

# Part 2: Revisiting the Hello Dataset

Enough about GPA (for now). Two weeks ago, you created a series of questions that made up the **Hello Dataset** and completed the survey by answering all of the questions made by students in DISCOVERY. 

Now, we will load this dataset again and briefly answer a few questions with data about YOU!

## Load the Hello Dataset

The "Hello Dataset" is available here:
```
https://waf.cs.illinois.edu/discovery/hello-sp23.csv
```

Use Python to load this dataset into a DataFrame called `df_hello`:

In [49]:
df_hello = pd.read_csv('https://waf.cs.illinois.edu/discovery/hello-sp23.csv')
df_hello

,Name,Section,"Are you a ""Type A"" or ""Type B"" personality?",Are you a morning person?,Are you an international student?,Are you an only child?,Are you from the Chicagoland area?,Do you consider your home to be in the United States or Abroad?,Are you in-state or out-of-state?,Are you tired?,...,What college is your major a part of?,What do you think is the hardest college major?,What genre of music do you listen to?,What is the best boba place in Urbana-Champaign?,What is your favorite color?,What is your favorite food?,What is your favorite music artist?,What is your favorite TV show?,What's your favorite social media app?,Which European country would you like to visit?
0,Prof Karle,AL1,"Type B (patient, flexible, laid-back)",No,No,No,No,United States,In-State,Yes,...,LAS,Computer Science,pop,LaTea,pink,Tacos,Taylor Swift,How to Get Away with Murder,Instagram,Italy
1,Prof Wade,AL1,"Type A (ambitious, competitive, aggressive)",No,No,No,No,United States,In-State,No,...,Grainger,CS,Pop,IDK?,Purple,BBQ,Taylor Swift,NaN,YouTube,Spain
2,Harsh,AYB,"Type A (ambitious, competitive, aggressive)",Yes,Yes,No,No,United States,Out-of-State,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Norman,AYO,"Type B (patient, flexible, laid-back)",No,Yes,No,No,Abroad,Out-of-State,No,...,Gies,Math,Jazz,Tea Moji,Blue,NaN,NaN,Breaking Bad,Discord,Switzerland
4,Christ`,AYM,"Type A (ambitious, competitive, aggressive)",Yes,No,No,Yes,United States,In-State,No,...,Information Scineces,Chemical Engineering,Hip Hop,I don't know,Red,Plantain chips,J. Cole,BMF,Instagram,Portugal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,Maryam,AYC,"Type A (ambitious, competitive, aggressive)",No,No,No,Yes,United States,In-State,Yes,...,iSchool,CS,R&B,Tiger Sugar,Green,Sushi,The Weeknd,One Tree Hill,TikTok,Montenegro
369,Nick,AYB,"Type A (ambitious, competitive, aggressive)",No,Yes,Yes,No,Abroad,Out-of-State,Yes,...,LAS,CS,Rap,Teamoji,White,Hot pot,Taylor Swift,Office,Twitter,France
370,Bowei,AYE,"Type B (patient, flexible, laid-back)",No,Yes,Yes,No,Abroad,Out-of-State,Yes,...,LAS,Computer Science,pop,Kungfu Tea,blue,Chinese,Jay Chou,Young Sheldon,WeChat,England
371,Sean,AYF,"Type B (patient, flexible, laid-back)",No,No,No,Yes,United States,In-State,No,...,Gies,Physics,Pop,KFT,Red,Sushi,Bruno Mars,The Office,Twitter,Sweden
372,TA Yiming,"AYO, AYQ","Type A (ambitious, competitive, aggressive)",No,Yes,Yes,No,Abroad,In-State,No,...,Statistics,Programming,Pop music,No idea,Purple,Beef,Dao Lang,News,WeChat,Greece

### 🔬 Test Case Checkpoint 🔬

In [50]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert(len(df_hello) == 373), "This is not the Hello dataset you're looking for. Check the URL."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

## Classes v. Sleep

With the Hello Dataset, we are going to briefly explore two quantitative questions posed and answered by all DISCOVERY students and staff:
- How many hours do you sleep in a day?
- How many classes are you taking this semester?

### Puzzle 2.1: Observation Subsets

In this situation, let's define the daily routine of **6 or more hours** of sleep as "good sleep" and any less to be defined as "bad sleep".

From this, create two DataFrames that contain subsets of the Hello Dataset: 
- `good_sleep`: including everyone who gets "good sleep" on average ($\space \geq 6 \space$)
- `bad_sleep`: including everyone who gets "bad sleep" on average ($\space < 6 \space$)

The `sleep` question has been provided to you as a **string** for ease of DataFrame column access.

In [51]:
sleep = 'How many hours do you sleep in a day?'
good_sleep = df_hello[df_hello[sleep] >= 6]
good_sleep

,Name,Section,"Are you a ""Type A"" or ""Type B"" personality?",Are you a morning person?,Are you an international student?,Are you an only child?,Are you from the Chicagoland area?,Do you consider your home to be in the United States or Abroad?,Are you in-state or out-of-state?,Are you tired?,...,What college is your major a part of?,What do you think is the hardest college major?,What genre of music do you listen to?,What is the best boba place in Urbana-Champaign?,What is your favorite color?,What is your favorite food?,What is your favorite music artist?,What is your favorite TV show?,What's your favorite social media app?,Which European country would you like to visit?
0,Prof Karle,AL1,"Type B (patient, flexible, laid-back)",No,No,No,No,United States,In-State,Yes,...,LAS,Computer Science,pop,LaTea,pink,Tacos,Taylor Swift,How to Get Away with Murder,Instagram,Italy
1,Prof Wade,AL1,"Type A (ambitious, competitive, aggressive)",No,No,No,No,United States,In-State,No,...,Grainger,CS,Pop,IDK?,Purple,BBQ,Taylor Swift,NaN,YouTube,Spain
2,Harsh,AYB,"Type A (ambitious, competitive, aggressive)",Yes,Yes,No,No,United States,Out-of-State,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Norman,AYO,"Type B (patient, flexible, laid-back)",No,Yes,No,No,Abroad,Out-of-State,No,...,Gies,Math,Jazz,Tea Moji,Blue,NaN,NaN,Breaking Bad,Discord,Switzerland
5,TA Faaez,"AYB, AYC","Type B (patient, flexible, laid-back)",Yes,Yes,No,No,Abroad,Out-of-State,No,...,Grainger,Mathematics,Pop,Kung Fu Tea,Red,Ramen,The Weeknd,House of the Dragon,Instagram,Paris
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,Maryam,AYC,"Type A (ambitious, competitive, aggressive)",No,No,No,Yes,United States,In-State,Yes,...,iSchool,CS,R&B,Tiger Sugar,Green,Sushi,The Weeknd,One Tree Hill,TikTok,Montenegro
369,Nick,AYB,"Type A (ambitious, competitive, aggressive)",No,Yes,Yes,No,Abroad,Out-of-State,Yes,...,LAS,CS,Rap,Teamoji,White,Hot pot,Taylor Swift,Office,Twitter,France
370,Bowei,AYE,"Type B (patient, flexible, laid-back)",No,Yes,Yes,No,Abroad,Out-of-State,Yes,...,LAS,Computer Science,pop,Kungfu Tea,blue,Chinese,Jay Chou,Young Sheldon,WeChat,England
371,Sean,AYF,"Type B (patient, flexible, laid-back)",No,No,No,Yes,United States,In-State,No,...,Gies,Physics,Pop,KFT,Red,Sushi,Bruno Mars,The Office,Twitter,Sweden
372,TA Yiming,"AYO, AYQ","Type A (ambitious, competitive, aggressive)",No,Yes,Yes,No,Abroad,In-State,No,...,Statistics,Programming,Pop music,No idea,Purple,Beef,Dao Lang,News,WeChat,Greece

In [52]:
bad_sleep = df_hello[df_hello[sleep] < 6]
bad_sleep

,Name,Section,"Are you a ""Type A"" or ""Type B"" personality?",Are you a morning person?,Are you an international student?,Are you an only child?,Are you from the Chicagoland area?,Do you consider your home to be in the United States or Abroad?,Are you in-state or out-of-state?,Are you tired?,...,What college is your major a part of?,What do you think is the hardest college major?,What genre of music do you listen to?,What is the best boba place in Urbana-Champaign?,What is your favorite color?,What is your favorite food?,What is your favorite music artist?,What is your favorite TV show?,What's your favorite social media app?,Which European country would you like to visit?
4,Christ`,AYM,"Type A (ambitious, competitive, aggressive)",Yes,No,No,Yes,United States,In-State,No,...,Information Scineces,Chemical Engineering,Hip Hop,I don't know,Red,Plantain chips,J. Cole,BMF,Instagram,Portugal
25,Ibrahim,AYK,"Type B (patient, flexible, laid-back)",Yes,No,No,Yes,United States,In-State,Yes,...,School of Information Sciences (ISchool),Biochemical Engineering,Everything,Kung Fu Tea,Yellow,Sandwiches,Stupendium,Community,Reddit,Istanbul
36,Aanvi,AYO,"Type A (ambitious, competitive, aggressive)",Yes,Yes,No,No,Abroad,Out-of-State,Yes,...,Grainger,Computer Engineering,Pop,kungFu tea,Blue,Bhelpuri,Charlie Puth,Tarak Mehta ka Ulta Chashma,Instagram,Norway
46,Joy,AYA,"Type B (patient, flexible, laid-back)",No,No,No,Yes,United States,In-State,No,...,Gies,mathematics,everything,cocomero,Black,roce,Drake,How To Get Away With Murder,Instagram,France
48,Ani,AYA,"Type B (patient, flexible, laid-back)",No,Yes,No,No,United States,Out-of-State,Yes,...,Grainger Engineering,Electrical Engineering,Rock,Infinitea,Blue,Crunchwrap Supreme,Led Zeppelin,Black Mirror,Reddit,Spain
68,Marshall,AYD,"Type B (patient, flexible, laid-back)",Yes,No,No,No,United States,In-State,Yes,...,LAS,Art,Alt-Rock,None of them,Green,Pierogies,JAWNY,Inside Job,Reddit,Iceland
73,TA Evangelos,"AYE, AYI","Type B (patient, flexible, laid-back)",Yes,Yes,No,No,United States,Out-of-State,No,...,1,Mathematics,Rock music,I don't know,Grey,Pasta,Hilary Hahn,Dark,Instagram,Denmark
109,Yoshee,AYM,"Type A (ambitious, competitive, aggressive)",No,Yes,Yes,No,Abroad,Out-of-State,Yes,...,Grainger,ECE,Low-fi,Teamoji,Red,NaN,One Direction,How I Met Your Mother,NaN,Switzerland
138,Ausar,AYA,"Type B (patient, flexible, laid-back)",No,No,No,Yes,United States,In-State,Yes,...,ACES,mechanical engineering,"hip hop, rock, r&b",NaN,green,Cheeseburgers,"Kanye west, drake, j cole","The boys, Rick and Morty",Instagram,italy
157,CA Ram,AYP,"Type B (patient, flexible, laid-back)",Yes,Yes,Yes,No,Abroad,Out-of-State,Yes,...,LAS,Mathematics,K-Pop,Teamoji,Blue,Ramen,TWICE,STAT 385 video lessons,Discord,Switzerland
174,Vedaant,AYQ,"Type B (patient, flexible, laid-back)",Yes,Yes,Yes,No,Abroad,Out-of-State,Yes,...,LAS,Physics,Classical,Kung Fu,Purple,Pizza,Arijit Singh,The Boys,Instagram,Italy
175,Shiya,AYM,"Type B (patient, flexible, laid-back)",No,Yes,No,No,Abroad,Out-of-State,Yes,...,Grainger,ECE,Rock,Kung Fu Tea,Purple,pasta,Linkin Park,FRIENDS,Whatsapp,Greece
184,Goose,AYP,"Type B (patient, flexible, laid-back)",Yes,No,No,Yes,United States,In-State,Yes,...,iSchool,engineering,rap,NaN,green,kitfo,Juice WRLD,too many to pick,snapchat,england
188,Emily,AYI,"Type B (patient, flexible, laid-back)",Yes,No,No,No,United States,Out-of-State,Yes,...,I school,Computer Engineering,Pop Chill,Tenko,Blue,Ice cream,Olivia Rodrigo,Singles Inferno,Instagram,France
197,Toby,AYK,"Type B (patient, flexible, laid-back)",Yes,No,No,Yes,United States,In-State,Yes,...,I-School,something in engineering,indie/alt,i don't like boba,navy blue,Indian Food,Clairo/Wallows,Gilmore Girls,TikTok,France
200,Ayares,AYO,"Type A (ambitious, competitive, aggressive)",Yes,No,Yes,Yes,United States,In-State,Yes,...,LAS,Engineering,Rock,Kung Fu Tea,Dark Green,Mexican,Mitski,Severance,Pinterest,Italy
218,Anthony,AYO,"Type B (patient, flexible, laid-back)",No,Yes,Yes,No,Abroad,Out-of-State,Yes,...,LAS,Data Science,All,Yuan cha,Black,Sashimi,Eason Chen,Non,Tiktok Chinese version,Iceland
251,Sam,AYP,"Type B (patient, flexible, laid-back)",No,No,No,No,Abroad,In-State,Yes,...,LAS,Electrical Engineering,Indie Rock,Teamoji,Blue,pasta,Good Kid,Umbrella Academy,None,Sweden
252,Janella,AYD,"Type B (patient, flexible, laid-back)",No,No,No,Yes,United States,In-State,Yes,...,iSchool,Engineering,J-POP,KFT,green,Sushi,Joji,Criminal Minds,TikTok,Italy
271,Guillermo,AYI,"Type A (ambitious, competitive, aggressive)",Yes,No,No,No,United States,In-State,Yes,...,ACES,IOnknow tbh,Any except country,Make it yourself,Blue,Wings,Kendrick,It's Always Sunny In Philadelphia,Twitter,Spain
297,Jose,AYE,"Type B (patient, flexible, laid-back)",Yes,No,No,Yes,United States,In-State,No,...,ACES,Engineering,Hip Hop,I don't know,red,Tamales,G herbo,The good doctor,Snapchat,Germany
300,Peter,AYP,"Type A (ambitious, competitive, aggressive)",Yes,Yes,No,No,Abroad,Out-of-State,Yes,...,Gies,CS,country,Tiger Sugar,blue,Thai food,Bruno Mars,4kings,Instagram,France
301,Santos,AYF,"Type A (ambitious, competitive, aggressive)",No,No,No,Yes,United States,In-State,Yes,...,LAS,Computer Science,Rock,I don't know,Green,Tacos,Vicente Fernandez,Malcolm in the middle,Youtube,Italy
310,hannah,AYD,"Type B (patient, flexible, laid-back)",No,No,No,Yes,United States,In-State,Yes,...,gies,engineering,pop,tiger sugar,purple,skittles,ruel,the office,tiktok,germany
330,Skylar,AYO,"Type B (patient, flexible, laid-back)",No,Yes,No,No,Abroad,In-State,Yes,...,DGS,math,Pop Rock R&B,moge tea,white,chicken wings!!!!,Adele,2 Broken girls,instagram,Iceland
334,Mickie,AYB,"Type A (ambitious, competitive, aggressive)",No,No,No,No,United States,In-State,Yes,...,iSchool,Engineering,Pop,Cafe Bene,Orange,Crawfish,Kennie JD,Schitt's Creek,Snapchat,Spain
344,Shynna,AYK,"Type B (patient, flexible, laid-back)",No,No,No,Yes,United States,In-State,Yes,...,Gies College of Business,Aerospace Engineering,Indie Rock,Teamoji,Forest Green,Tacos,Kendrick Lamar,Naruto,instagram,Iceland

### 🔬 Test Case Checkpoint 🔬

In [53]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert(len(good_sleep) == 346  ), "Double check your conditional used to create df_goodsleep from df_hello - remember, good sleep is response values of 6 hours or more"
assert(len(bad_sleep) == 27 ), "Double check your conditional used to create df_badsleep from df_hello - remember, bad sleep is response values of less than 6 hours"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 2.2: Average Number of Classes by Group

Now find the **average number of classes** of each group (`good_sleep` and `bad_sleep`):

- The `df['column name'].mean()` function returns the mean of all values in the specified column of `df`
- The `classes` question has been provided to you as a **string** for ease of DataFrame column access.

In [55]:
classes = 'How many classes are you taking this semester?'
good_sleep_avg_classes = good_sleep[classes].mean()
good_sleep_avg_classes

5.037900874635569

In [56]:
bad_sleep_avg_classes = bad_sleep[classes].mean()
bad_sleep_avg_classes

5.111111111111111

### 🔬 Test Case Checkpoint 🔬

In [57]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert(math.isclose(good_sleep_avg_classes,  5.037900874635569)), "The average number of classes for those with good sleep does not appear to have been correctly calculated"
assert(math.isclose(bad_sleep_avg_classes,  5.111111111111111)), "The average number of classes for those with bad sleep does not appear to have been correctly calculated"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Analyis: Classes v. Sleeptime

**Q: What is the relationship between classes and daily sleep time?  Can you think of a possible *confounding variable* in the observed relationship (or lack thereof) between classes and daily sleep time?** Write at least three complete sentences.

The relationship between classes and daily sleep time is that people with good sleep take less classes on average. A possible confounder for this could be the individuals major and how many hours they have to spend studying per class. Another counfounder could be credit hours because some classes may be 1 or 2 credit hours while others are 4 credit hours, therefore requiring more hours awake and dedicated to studying.

<hr style="color: #DD3403;">

# Submission

You're almost done!  All you need to do is to commit your lab to GitHub:

1.  ⚠️ **Make certain to save your work.** ⚠️ To do this, go to **File => Save All**

2.  After you have saved, exit this notebook and follow the Canvas instructions to commit this lab to your Git repository!

3. Your TA will grade your submission and provide you feedback after the lab is due. :)